### ISSUE TITLE
Design of alt-tab popup with css

### ISSUE THREAD

**Issue by luigifab** [mate-desktop/marco#788]
I've just updated my CSS theme for XFCE's AltTab (`#xfwm-tabwin`), and I see that Mate's AltTab has a kind of border-radius with a white background (when background window is mate-terminal or geany). See:

![Image](https://github.com/user-attachments/assets/98a36b08-bf16-4ce7-9872-4b06f281635e)

What are the CSS nodes for it?
Is there an id or a name?

My idea is to remove the border-radius.
Thanks!

_Marco 1.26.2 + Mate 1.26.2 / Debian Testing_

**Comment by lukefromdc** [comment]
I do not know myself, and this is the sort of thing it might not be possible to run GtkInspector on.
In the source code a string search for `gtk_widget_set_name` comes up empty but we do have
```

      gtk_style_context_add_class (gtk_widget_get_style_context (GTK_WIDGET (popup->window)),
                                   GTK_STYLE_CLASS_OSD);
```
adding the OSD style class to the tab popup

**Comment by luigifab** [comment]
Yes, it is, this is the frame border from my theme:

```css
frame > border {
	border: 1px solid @frame_border;
	border-radius: 2.5px;
	box-shadow:
		inset -1px -1px alpha(@entry_bg, 0.27),
		inset 1px 1px alpha(@frame_border, 0.17);
}
```
